services:
  db:
    image: mysql:8.4
    container_name: mp2_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    restart: unless-stopped
  
  app:
    image: haroldasleknius/miniproject2:latest
    container_name: mp2_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5454:5454"
    restart: unless-stopped

volumes:
  data: