services:
  db:
    image: mysql:8.4
    container_name: mp2_mysql
    environment:
      MYSQL_DATABASE: miniproject2
      MYSQL_USER: haroldas
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
  
  app:
    image: ${IMAGE_FULL}
    container_name: mp2_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: miniproject2
      DB_USER: haroldas
      DB_PASSWORD: pass
      USER: jenkins
      LOGNAME: jenkins
      HOME: /tmp
