services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: miniproject2
      MYSQL_USER: haroldas
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass --silent"]
      interval: 2s
      timeout: 2s
      retries: 30
  
  app:
    image: ${IMAGE_FULL}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: miniproject2
      DB_USER: haroldas
      DB_PASSWORD: pass
      USER: jenkins
      LOGNAME: jenkins
      HOME: /tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:5454/ >/dev/null || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 60
