FROM python

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY logsetup.py /app/

COPY data_shipper.py /app/

CMD ["python", "-u", "data_shipper.py"]