[project]
name = "miniproject2"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
	"Flask",
	"Faker",
]

[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["miniproject2"]


