apiVersion: apps/v1
kind: Deployment
metadata:
  name: esports-api
  namespace: esportsapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: esports-api
  template:
    metadata:
      labels:
        app: esports-api
    spec:
      containers:
        - name: esports-api
          image: esportsapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5454
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: LOG_FORMAT
              value: "json"
            - name: LOG_LEVEL
              value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: esports-api-svc
  namespace: esportsapi
spec:
  type: NodePort
  selector:
    app: esports-api
  ports:
    - name: http
      port: 5454
      targetPort: 5454
      nodePort: 30101
