apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
  namespace: elk
spec:
  version: 9.1.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms1g -Xmx1g"
            resources:
              requests:
                memory: "1.5Gi"
              limits:
                memory: "2Gi"
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: elk
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: elastic-search
  ports:
    - name: https
      port: 9200
      targetPort: 9200
      nodePort: 30102