apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: log-system
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: k8s-containers
        paths: ["/var/log/containers/*.log"]
        prospector.scanner.symlinks: true
        parsers:
          - container: {}
        close_inactive: 5m

    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          node: ${NODE_NAME}
          default_indexers.enabled: true
          default_matchers.enabled: false
          matchers:
            - logs_path:
                logs_path: /var/log/containers/
            - logs_path:
                logs_path: /var/log/pods/
          labels.dedot: true
          annotations.dedot: true
      - drop_event:
          when:
            or:
              - equals:
                  kubernetes.container.name: "kindnet-cni"
              - equals:
                  kubernetes.container.name: "filebeat"
      - add_host_metadata: ~
      - add_cloud_metadata: ~

    # output.elasticsearch:
    # hosts: ["${ES_URL}"]
    # username: ${ES_USER}
    # password: ${ES_PASS}
    # ssl.verification_mode: none

    output.logstash:
      hosts: ["logstash-ls-beats.elk.svc:5044"]

    logging.level: info
    logging.to_files: false
    monitoring.enabled: false
