apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: esportsapi
type: Opaque
stringData:
  MYSQL_DATABASE: pro_esports
  MYSQL_USER: haroldas
  MYSQL_PASSWORD: haroldas123
  MYSQL_ROOT_PASSWORD: Haroldas123!